//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRY_Taglitore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Ordenes
    {
        [Display(Name ="#")]
        public int OrdenID { get; set; }
        [Display(Name = "Nro de mesa")]
        public int Mesa { get; set; }
        [Display(Name = "Nombre de cliente")]
        public string Cliente { get; set; }
        [Display(Name = "Nombre de mesero")]
        public string Mesero { get; set; }
        [Display(Name = "Nombre del platillo")]
        public string platillo { get; set; }
        [Display(Name = "Cantidad de platillos")]
        public int cantidad { get; set; }
    }
}
